UKSM 0.1.2.3
Changes to the UKSM 0.1.2.3 patch provided by KernelDedup
(http://kerneldedup.org/en/) :

* Fix : mm/uksm.c:169:23: warning: initialization discards 'const'
qualifier from pointer target type
* Fix : mm/uksm.c:198:0: warning: "U64_MAX" redefined
* Fix : mm/uksm.c:1621:10: error: implicit declaration of function
'compound_trans_head'
* Make everything compatible with ARM64 in general

Note to ARM users :
You only need to change :
* elif defined(CONFIG_ARM64) to elif defined(CONFIG_ARM) in uksm.c
The above line is used to fix a compilation error, in case that ever
happens